"""Phase5 WhatsApp Consent

Revision ID: 8cbfadeeee1c
Revises: c4df029dd3a9
Create Date: 2026-09-07 21:46:51.854705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cbfadeeee1c'
down_revision: Union[str, None] = 'c4df029dd3a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('whatsapp_consent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('guests', sa.Column('consent_source', sa.String(length=50), nullable=True))
    op.add_column('guests', sa.Column('consent_text_version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'consent_text_version')
    op.drop_column('guests', 'consent_source')
    op.drop_column('guests', 'whatsapp_consent_at')
    # ### end Alembic commands ###
