"""Add missing match columns

Revision ID: a2a3c194f9e0
Revises: 0016_day24_crypto_phase_3
Create Date: 2026-08-26 20:09:12.629133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a3c194f9e0'
down_revision: Union[str, None] = '0016_day24_crypto_phase_3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('cluster_rank', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('ranked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_matches_gallery', 'matches', ['guest_id', 'status', 'cluster_rank', sa.text('similarity DESC')], unique=False)
    op.add_column('photo_faces', sa.Column('sharpness_score', sa.Float(), nullable=True))
    op.add_column('photo_faces', sa.Column('eye_open_score', sa.Float(), nullable=True))
    op.add_column('photo_faces', sa.Column('smile_score', sa.Float(), nullable=True))
    op.add_column('photo_faces', sa.Column('frontality_score', sa.Float(), nullable=True))
    op.add_column('photo_faces', sa.Column('exposure_score', sa.Float(), nullable=True))
    op.add_column('photo_faces', sa.Column('composite_quality', sa.Float(), nullable=True))
    op.add_column('photo_faces', sa.Column('scoring_model_version', sa.String(length=100), nullable=True))
    op.add_column('photo_faces', sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('photo_faces', sa.Column('erasure_redacted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_faces', 'erasure_redacted')
    op.drop_column('photo_faces', 'scored_at')
    op.drop_column('photo_faces', 'scoring_model_version')
    op.drop_column('photo_faces', 'composite_quality')
    op.drop_column('photo_faces', 'exposure_score')
    op.drop_column('photo_faces', 'frontality_score')
    op.drop_column('photo_faces', 'smile_score')
    op.drop_column('photo_faces', 'eye_open_score')
    op.drop_column('photo_faces', 'sharpness_score')
    op.drop_index('ix_matches_gallery', table_name='matches')
    op.drop_column('matches', 'ranked_at')
    op.drop_column('matches', 'cluster_rank')
    # ### end Alembic commands ###
