"""Phase9_Biometric_Retention

Revision ID: a59c236c14f2
Revises: a17d960eaf48
Create Date: 2026-09-08 00:08:58.975153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59c236c14f2'
down_revision: Union[str, None] = 'a17d960eaf48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('biometric_consent_text_version', sa.String(length=50), nullable=True))
    op.add_column('guests', sa.Column('biometrics_purged_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'biometrics_purged_at')
    op.drop_column('guests', 'biometric_consent_text_version')
    # ### end Alembic commands ###
