# pyright: reportArgumentType=false
# pyright: reportGeneralTypeIssues=false
"""perceptual_dedup

Revision ID: bc5faf281906
Revises: 0014
Create Date: 2026-08-15 16:37:05.222929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc5faf281906'
down_revision: Union[str, None] = '0014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('membership_hash', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('representative_photo_id', sa.UUID(), nullable=True),
    sa.Column('mean_quality', sa.Float(), nullable=True),
    sa.Column('time_span_s', sa.Float(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['representative_photo_id'], ['photos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'membership_hash', name='uq_photoclusters_event_membership')
    )
    op.create_index(op.f('ix_photo_clusters_event_id'), 'photo_clusters', ['event_id'], unique=False)
    op.drop_index('ix_event_photos_event_id', table_name='event_photos')
    op.create_index(op.f('ix_event_photos_id'), 'event_photos', ['id'], unique=False)
    op.drop_index('ix_face_embeddings_embedding_ivfflat', table_name='face_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('guest_access_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.alter_column('guest_access_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.drop_constraint('guest_access_tokens_token_hash_key', 'guest_access_tokens', type_='unique')
    op.drop_index('ix_guest_access_tokens_guest_revoked', table_name='guest_access_tokens')
    op.create_index(op.f('ix_guest_access_tokens_guest_id'), 'guest_access_tokens', ['guest_id'], unique=False)
    op.alter_column('match_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.alter_column('match_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.alter_column('matches', 'matched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.alter_column('matches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.alter_column('matches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.drop_index('ix_matches_event_review', table_name='matches', postgresql_where="((decision)::text = 'review'::text)")
    op.drop_index('ix_matches_guest_status_sim', table_name='matches')
    op.create_index(op.f('ix_matches_event_id'), 'matches', ['event_id'], unique=False)
    op.create_index(op.f('ix_matches_guest_id'), 'matches', ['guest_id'], unique=False)
    op.create_index(op.f('ix_matches_photo_id'), 'matches', ['photo_id'], unique=False)
    op.drop_index('ix_notification_logs_status_retry', table_name='notification_logs')
    op.drop_constraint('uq_notification_logs_dedupe', 'notification_logs', type_='unique')
    op.alter_column('photo_faces', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.alter_column('photo_faces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.drop_index('ix_photo_faces_event_matchable', table_name='photo_faces')
    op.create_index(op.f('ix_photo_faces_event_id'), 'photo_faces', ['event_id'], unique=False)
    op.create_index(op.f('ix_photo_faces_photo_id'), 'photo_faces', ['photo_id'], unique=False)
    op.drop_index('ix_photo_matches_unique_photo_guest', table_name='photo_matches')
    op.create_index(op.f('ix_photo_matches_id'), 'photo_matches', ['id'], unique=False)
    op.add_column('photos', sa.Column('phash', sa.BigInteger(), nullable=True))
    op.add_column('photos', sa.Column('dhash', sa.BigInteger(), nullable=True))
    op.add_column('photos', sa.Column('hash_computed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('photos', sa.Column('dup_cluster_id', sa.UUID(), nullable=True))
    op.add_column('photos', sa.Column('is_cluster_representative', sa.Boolean(), nullable=True))
    storage_tier_enum = postgresql.ENUM('local', 's3', name='storage_tier_enum')
    storage_tier_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('photos', sa.Column('storage_tier', sa.Enum('local', 's3', name='storage_tier_enum'), nullable=True))
    op.alter_column('photos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.alter_column('photos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.drop_index('ix_photos_batch_status', table_name='photos')
    op.drop_index('ix_photos_event_status', table_name='photos')
    op.create_index(op.f('ix_photos_batch_id'), 'photos', ['batch_id'], unique=False)
    op.create_index(op.f('ix_photos_dup_cluster_id'), 'photos', ['dup_cluster_id'], unique=False)
    op.create_index(op.f('ix_photos_event_id'), 'photos', ['event_id'], unique=False)
    op.create_index(op.f('ix_photos_hash_computed_at'), 'photos', ['hash_computed_at'], unique=False)
    op.create_index(op.f('ix_photos_status'), 'photos', ['status'], unique=False)
    op.create_index(op.f('ix_photos_storage_tier'), 'photos', ['storage_tier'], unique=False)
    op.create_foreign_key(None, 'photos', 'photo_clusters', ['dup_cluster_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_selfie_search_logs_event_created', table_name='selfie_search_logs')
    op.drop_index('ix_selfie_search_logs_ip_created', table_name='selfie_search_logs')
    op.create_index(op.f('ix_selfie_search_logs_created_at'), 'selfie_search_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_selfie_search_logs_event_id'), 'selfie_search_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_selfie_search_logs_ip_hash'), 'selfie_search_logs', ['ip_hash'], unique=False)
    op.alter_column('upload_batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uq_zip_archives_guest_match_hash', 'zip_archives', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_zip_archives_guest_match_hash', 'zip_archives', ['guest_id', 'match_set_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('upload_batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.drop_index(op.f('ix_selfie_search_logs_ip_hash'), table_name='selfie_search_logs')
    op.drop_index(op.f('ix_selfie_search_logs_event_id'), table_name='selfie_search_logs')
    op.drop_index(op.f('ix_selfie_search_logs_created_at'), table_name='selfie_search_logs')
    op.create_index('ix_selfie_search_logs_ip_created', 'selfie_search_logs', ['ip_hash', 'created_at'], unique=False)
    op.create_index('ix_selfie_search_logs_event_created', 'selfie_search_logs', ['event_id', 'created_at'], unique=False)
    op.drop_constraint(None, 'photos', type_='foreignkey')  # type: ignore
    op.drop_index(op.f('ix_photos_storage_tier'), table_name='photos')
    op.drop_index(op.f('ix_photos_status'), table_name='photos')
    op.drop_index(op.f('ix_photos_hash_computed_at'), table_name='photos')
    op.drop_index(op.f('ix_photos_event_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_dup_cluster_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_batch_id'), table_name='photos')
    op.create_index('ix_photos_event_status', 'photos', ['event_id', 'status'], unique=False)
    op.create_index('ix_photos_batch_status', 'photos', ['batch_id', 'status'], unique=False)
    op.alter_column('photos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.alter_column('photos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.drop_column('photos', 'storage_tier')
    op.drop_column('photos', 'is_cluster_representative')
    op.drop_column('photos', 'dup_cluster_id')
    op.drop_column('photos', 'hash_computed_at')
    op.drop_column('photos', 'dhash')
    op.drop_column('photos', 'phash')
    op.drop_index(op.f('ix_photo_matches_id'), table_name='photo_matches')
    op.create_index('ix_photo_matches_unique_photo_guest', 'photo_matches', ['event_photo_id', 'guest_id'], unique=True)
    op.drop_index(op.f('ix_photo_faces_photo_id'), table_name='photo_faces')
    op.drop_index(op.f('ix_photo_faces_event_id'), table_name='photo_faces')
    op.create_index('ix_photo_faces_event_matchable', 'photo_faces', ['event_id', 'is_matchable', 'matched_at'], unique=False)
    op.alter_column('photo_faces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.alter_column('photo_faces', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.create_unique_constraint('uq_notification_logs_dedupe', 'notification_logs', ['guest_id', 'channel', 'notification_type', 'dedupe_key'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_notification_logs_status_retry', 'notification_logs', ['status', 'next_retry_at'], unique=False)
    op.drop_index(op.f('ix_matches_photo_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_guest_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_event_id'), table_name='matches')
    op.create_index('ix_matches_guest_status_sim', 'matches', ['guest_id', 'status', sa.text('similarity DESC')], unique=False)
    op.create_index('ix_matches_event_review', 'matches', ['event_id', 'decision'], unique=False, postgresql_where="((decision)::text = 'review'::text)")
    op.alter_column('matches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.alter_column('matches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.alter_column('matches', 'matched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.alter_column('match_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.alter_column('match_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.drop_index(op.f('ix_guest_access_tokens_guest_id'), table_name='guest_access_tokens')
    op.create_index('ix_guest_access_tokens_guest_revoked', 'guest_access_tokens', ['guest_id', 'revoked_at'], unique=False)
    op.create_unique_constraint('guest_access_tokens_token_hash_key', 'guest_access_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('guest_access_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.alter_column('guest_access_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))  # type: ignore
    op.create_index('ix_face_embeddings_embedding_ivfflat', 'face_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_event_photos_id'), table_name='event_photos')
    op.create_index('ix_event_photos_event_id', 'event_photos', ['event_id'], unique=False)
    op.drop_index(op.f('ix_photo_clusters_event_id'), table_name='photo_clusters')
    op.drop_table('photo_clusters')
    # ### end Alembic commands ###
