http:
  middlewares:
    sec-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
    ratelimit:
      rateLimit:
        average: 100
        burst: 50
    compress:
      compress: {}
